---
grails:
  profile: "@grails.profile@"
  codegen:
    defaultPackage: "@grails.codegen.defaultPackage@"
  gorm:
    reactor:
      # Whether to translate GORM events into Reactor events
      # Disabled by default for performance reasons
      events: false
info:
  app:
    name: "@info.app.name@"
    version: "@info.app.version@"
    grailsVersion: "@info.app.grailsVersion@"
spring:
  main:
    banner-mode: "off"
  groovy:
    template:
      check-template-location: false

# We have these enabled; default grails does not
endpoints:
  enabled: true
  jmx:
    enabled: true
  info:
    enabled: true

---
grails:
  mime:
    disable:
      accept:
        header:
          userAgents:
            - Gecko
            - WebKit
            - Presto
            - Trident
    types:
      all: "*/*"
      atom: application/atom+xml
      css: text/css
      csv: text/csv
      form: application/x-www-form-urlencoded
      html:
        - text/html
        - application/xhtml+xml
      js: text/javascript
      json:
        - application/json
        - text/json
      multipartForm: multipart/form-data
      pdf: application/pdf
      rss: application/rss+xml
      text: text/plain
      hal:
        - application/hal+json
        - application/hal+xml
      xml:
        - text/xml
        - application/xml
  urlmapping:
    cache:
      maxsize: 1000
  controllers:
    defaultScope: singleton
  converters:
    encoding: UTF-8
  views:
    default:
      codec: html
    gsp:
      encoding: UTF-8
      htmlcodec: xml
      codecs:
        expression: html
        scriptlets: html
        taglib: none
        staticparts: none
endpoints:
  jmx:
    unique-names: true

---
grails:
  plugin:
    auditLog:
      auditDomainClassName: "edu.rowan.AuditTrail"
    mail:
      host: "mail.rowan.edu"
      port: 25
    springsecurity:
      cas:
        serverUrlPrefix: "https://login.rowan.edu/cas"
        active: true
        loginUri: "/login"
        sendRenew: false
        serverUrlEncoding: "UTF-8"
        key: "grails-spring-security-cas"
        artifactParameter: "ticket"
        serviceParameter: "service"
        filterProcessesUrl: "/login/authenticate"
        proxyReceptorUrl: "/secure/receptor"
        useSingleSignout: true
        proxyCallbackUrl: null
      rejectIfNoRule: false
      fii:
        rejectPublicInvocations: false
      providerNames: ["casAuthenticationProvider"]
      userLookup:
        userDomainClassName: edu.rowan.AppUser
        authorityJoinClassName: edu.rowan.AppUserAppRole
      authority:
        className: edu.rowan.AppRole
      securityConfigType: Annotation
      controllerAnnotations:
        staticRules:
          - pattern: /
            access:
              - permitAll
          - pattern: /error
            access:
              - permitAll
          - pattern: /index
            access:
              - permitAll
          - pattern: /index.gsp
            access:
              - permitAll
          - pattern: /shutdown
            access:
              - permitAll
          - pattern: /assets/**
            access:
              - permitAll
          - pattern: /**/js/**
            access:
              - permitAll
          - pattern: /**/css/**
            access:
              - permitAll
          - pattern: /**/images/**
            access:
              - permitAll
          - pattern: /**/favicon.ico
            access:
              - permitAll
      filterChain:
        chainMap:
          - pattern: /assets/**
            filters: none
          - pattern: /**/js/**
            filters: none
          - pattern: /**/css/**
            filters: none
          - pattern: /**/images/**
            filters: none
          - pattern: /**/favicon.ico
            filters: none
          - pattern: /**
            filters: JOINED_FILTERS
---
hibernate:
  cache:
    queries: false
    use_second_level_cache: false
    use_query_cache: false
  flush:
    mode: AUTO
dataSource:
  pooled: true
  jmxExport: true
  driverClassName: oracle.jdbc.OracleDriver
  dialect: org.hibernate.dialect.Oracle10gDialect
  username: ${APP_DB_USERNAME}
  password: ${APP_DB_PASSWORD}
  properties:
    jmxEnabled: true
    initialSize: 5
    maxActive: 50
    minIdle: 5
    maxIdle: 25
    maxWait: 10000
    maxAge: 600000
    timeBetweenEvictionRunsMillis: 5000
    minEvictableIdleTimeMillis: 60000
    validationQuery: SELECT 1 from dual
    validationQueryTimeout: 3
    validationInterval: 15000
    testOnBorrow: true
    testWhileIdle: true
    testOnReturn: false
    jdbcInterceptors: ConnectionState
    defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED
environments:
  development:
    dataSource:
      dbCreate: create-drop
      url: jdbc:oracle:thin:@ldap://oid.rowan.edu:1639/PPRD,cn=OracleContext,dc=rowan,dc=edu
    grails:
      plugin:
        springsecurity:
          cas:
            serviceUrl: http://asa-dev:${APP_PORT_NUMBER}/login/authenticate
          logout:
            afterLogoutUrl: https://login.rowan.edu/cas/logout?service=http://asa-dev:${APP_PORT_NUMBER}
  test:
    dataSource:
      dbCreate: none
      url: jdbc:oracle:thin:@ldap://oid.rowan.edu:1639/FORTNGHT,cn=OracleContext,dc=rowan,dc=edu
    grails:
      plugin:
        springsecurity:
          cas:
            serviceUrl: https://${APP_TEST_URL}/login/authenticate
          logout:
            afterLogoutUrl: https://login.rowan.edu/cas/logout?service=https://${APP_TEST_URL}
  production:
    dataSource:
      dbCreate: none
      url: jdbc:oracle:thin:@ldap://oid.rowan.edu:1639/PROD,cn=OracleContext,dc=rowan,dc=edu
    grails:
      plugin:
        springsecurity:
          cas:
            serviceUrl: https://${APP_PROD_URL}/login/authenticate
          logout:
            afterLogoutUrl: https://login.rowan.edu/cas/logout?service=https://${APP_PROD_URL}
